version: "3.5"

services:
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8888
    ports:
      - "8888:8888"
    env_file:
      - .env
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
          max-size: "500M"
          max-file: "5"
